[package]
name = "fourbuttons"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clokwerk = "0.4.0"
crossbeam-channel = "0.5.10"
env_logger = "0.10.1"
log = "0.4.20"
rppal = "0.16.1"

[dependencies.rusqlite]
version = "0.30.0"
features = ["bundled"]
